spring:
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:57673/railway                             #localhost:5432/locationphormacie
    username: postgres
    password: d-56AB2Bf1bG*ABCbdedGgFcgD3-aA3-
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# server:
#   port: 9001
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
        
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/locationphormacie
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
##    database: postgresql
##    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days
#
##  jdbc:postgresql://localhost:5432/locationphormacie
